function Gauge(a,b){var c=document.getElementById(a),d=window.getComputedStyle(c,null);diffAngle=insAngle=minSide=null;b=b||{};this.style={width:~~d.width.substr(0,d.width.length-2),height:~~d.height.substr(0,d.height.length-2),font:d.fontFamily.substring(1,d.fontFamily.length-1),fontSize:d.fontSize,textColor:d.color};c.className="gauge";minSide=this.style.width<this.style.height?this.style.width:this.style.height;b={radius:b.radius||minSide/2*.7,apert:b.apert||225,insideText:b.insideText||!1,lineWidth:b.lineWidth||
2,color:b.color||"#51545B"};insAngle=360-b.apert;diffAngle=(180-insAngle)/2;this.dataGauge={el:c,centerX:this.style.width/2,centerY:this.style.height/2,startAngle:Math.PI/180*(insAngle+diffAngle),endAngle:Math.PI/180*diffAngle,deg:270};for(var e in b)this.dataGauge[e]=b[e];this.data=[];d=null;e=0;for(var f=null,g=0;g<c.childNodes.length;g++)d=c.childNodes[g],1==d.nodeType&&(f=d.getAttribute("data-color")||!1,null!==d.getAttribute("selected")&&(this.dataGauge.selected=e),this.data.push({text:d.innerHTML,
color:f}),e++);!0}
Gauge.prototype.createTumbler=function(){var a=this.dataGauge.el,b=document.createElement("div"),c=document.createElement("h3"),d=document.createElement("select"),e=document.createElement("button");b.className="gaugeTumbler";c.appendChild(document.createTextNode("Kuda"));e.appendChild(document.createTextNode("GO!"));for(var f=0;f<this.data.length;f++){var g=this.data[f],k=document.createElement("option");k.appendChild(document.createTextNode(g.text));k.value=g.angle;f==this.dataGauge.selected&&(k.selected=
!0);d.appendChild(k)}b.appendChild(c);b.appendChild(d);b.appendChild(e);a.appendChild(b);this.tmb={select:d,button:e,tmb:b}};Gauge.prototype.createCanvas=function(){var a=document.createElement("canvas");a.setAttribute("width",this.style.width);a.setAttribute("height",this.style.height);this.dataGauge.el.classList.add("gaugeCanvas");this.dataGauge.el.innerHTML="";this.dataGauge.el.appendChild(a);this.dataGauge.canvas=a};
Gauge.prototype.createCanvasArrow=function(){var a=document.createElement("canvas");a.setAttribute("width",this.style.width);a.setAttribute("height",this.style.height);a.className="gaugeArrow";this.dataGauge.el.appendChild(a);this.dataGauge.arrow=a};
Gauge.prototype.drawArc=function(){var a=this.dataGauge,b=a.canvas.getContext("2d");b.clearRect(0,0,this.style.width,this.style.height);b.beginPath();b.lineWidth=a.lineWidth;b.strokeStyle=a.color;b.arc(a.centerX,a.centerY,a.radius,a.startAngle,a.endAngle,!1);b.stroke();b.closePath()};
Gauge.prototype.drawScale=function(){var a=this.dataGauge,b=this.data.length,c=a.canvas.getContext("2d"),d=a.apert/(b-1)*(Math.PI/180),e=null,f=null,g=null,k=null,r=null,l=null,m=null,l=m=null,n=a.insideText?-1:1,t=20*n,u=10*n,n=27*n,f=a.startAngle,h=f+d/2,q=Math.floor(b/2),p=null;c.beginPath();c.textBaseline="middle";c.fillStyle=this.style.textColor;c.font=this.style.fontSize+" "+this.style.font;c.textAlign="right";for(e in this.data)c.strokeStyle=a.color,c.lineWidth=a.lineWidth,p=a.startAngle+d*
e,m=Math.cos(p),l=Math.sin(p),f=m*(a.radius+t)+a.centerX,g=l*(a.radius+t)+a.centerY,k=m*(a.radius+u)+a.centerX,r=l*(a.radius+u)+a.centerY,this.data[e].angle=180/Math.PI*p,m=m*(a.radius+n)+a.centerX,l=l*(a.radius+n)+a.centerY,c.moveTo(f,g),c.lineTo(k,r),0==e?(f=a.startAngle,h=f+d/2):e==b-1?(f=h,h+=d/2):(f=h,h+=d),this.data[e].color&&(c.stroke(),c.closePath(),c.beginPath(),c.lineWidth=4,c.strokeStyle=this.data[e].color,c.arc(a.centerX,a.centerY,a.radius,f,h,!1),c.stroke(),c.closePath(),c.beginPath()),
e<q&&(c.textAlign=a.insideText?"left":"right"),e==q&&(c.textAlign="center"),e>q&&(c.textAlign=a.insideText?"right":"left"),c.fillText(this.data[e].text,m,l);c.stroke();c.closePath()};Gauge.prototype.drawArrow=function(){var a=this.dataGauge,b=a.arrow.getContext("2d"),c=a.centerX,d=a.centerY;b.beginPath();b.lineWidth=1;b.fillStyle="#00C6FF";b.strokeStyle="#00C6FF";b.moveTo(c,d+3);b.lineTo(c+a.radius/1.2,d);b.lineTo(c,d-3);b.lineTo(c,d+3);b.arc(c,d,5,0,180,!1);b.stroke();b.fill();b.closePath()};
Gauge.prototype.rotateArrow=function(a){var b=this.dataGauge;a=a||this.data[b.selected].angle;b.deg<a?(a=-1*(360-a),b.deg=-1*a):b.deg=a;b.arrow.style.transform="rotate("+a+"deg)"};Gauge.prototype.bindEvent=function(){var a=this;this.tmb.button.onclick=function(){a.rotateArrow(a.tmb.select.options[a.tmb.select.selectedIndex].value)}};
Gauge.prototype.runDrawGauge=function(){this.createCanvas();this.createCanvasArrow();this.drawArc();this.drawScale();this.drawArrow();this.rotateArrow();this.createTumbler();this.bindEvent()};